### ISSUE TITLE
Add some unit tests?

### ISSUE THREAD

**Issue by JensRantil** [fimblo/generate-prompt#2]
I noticed there are no tests. Maybe add some? Either unit tests in C, or considering something like https://github.com/bats-core/bats-core since this project integrates with the shell?

**Comment by fimblo** [comment]
This idea I like. Will definitely do this.

**Comment by fimblo** [comment]
I kept on putting it off until I simply _had_ to have tests to be able to continue adding features. Even if it's a small program, it's getting too big to keep all details in my tiny brain :)

Thanks again for the tip! bats-core is useful.
