### ISSUE TITLE
Add CI?

### ISSUE THREAD

**Issue by JensRantil** [fimblo/generate-prompt#3]
I noticed that there is no CI such as Github Actions. At least currently it could check whether the code actually compiles. But down the road I guess you could add linting and/or [unit test execution](https://github.com/fimblo/generate-prompt/issues/2).

**Comment by fimblo** [comment]
Not really sure how this would help. Well, aside from your example - that it automatically runs the tests upon merge or something.

**Comment by fimblo** [comment]
This was a good idea. As you mentioned in another forum, showing that the code can be compiled is a good (first) step at showing that the code works. Thanks!
